Performance Enhancements for Web Viewer
AcademySoftwareFoundation/MaterialX pull request #1891
Opened 2024-06-18 15:54 UTC by kwokcb

## Performance Enhancements

- Add in dirty/refresh mechanism triggered by actions which require a re-render. Reduce big performance overhead of constantly re-rendering which can be quite slow for more complex shading models such as OpenPBR.
- Add in texture cache reuse using ThreeJS cache. Handle http/blob/data encodings properly.
- Add in sphere geometry as this is the lightest weight geometry performance-wise.

### Implementation Changes
- Simple implementation of adding in a refresh counter which get's incremented when an action calls to "require an update".
- Refresh look still does constant polling but will only re-render if refresh counter is > 0.
- The actions where refresh requests are added include:
  - material, geometry load (menu or drag-drop)
  - texture load
  - transform changes: camera, viewport resize , turntable
  - background texture toggle

Note: There is no refresh queue management (e.g. compressing the number of requests) so that all camera, property edits, turntable updates are queued. This will never be worse than what occurs before this change and is thus as "safe" as before (no refreshes will be "list". Re-render is gated by how often ThreeJS triggers a refresh/render.

@jstone-lucasfilm : This makes OpenPBR not max-out the GPU on my laptop and should help a fair bit with scenes with more textures such as the chess set as the texture cache is used. Will also help drag-drop.

2024-06-18 16:09 UTC, kwokcb commented on javascript/MaterialXView/source/helper.js
> +                if (value.startsWith('blob:'))
Blobs, embedded data and http references are no relative to a search path. This fixes it so users can use these texture URI specifications in their files.

2024-06-18 16:09 UTC, kwokcb commented on javascript/MaterialXView/source/helper.js
> +                const cachedTexture = checkCache && THREE.Cache.get(texturePath);
Do proper cache checking.

2024-06-18 16:09 UTC, kwokcb commented on javascript/MaterialXView/source/index.js
> +    // Only re-render when an update request was made
Re-render gated by requirement to refresh. All the `schedulUpdate()` calls triggers the requirment.

2024-06-18 16:09 UTC, kwokcb commented on javascript/MaterialXView/source/viewer.js
> +            try {
Small fix. Would "crash" sometimes on invalid files.

2024-07-13 22:35 UTC, jstone-lucasfilm requested changes
I really like all of the small fixes and improvements in this change, but I'm less convinced by the caching scheme, which runs counter to the rendering approach I see in other performance-focused web applications.  Additionally, the caching scheme has the side effect of making `viewer` an input to `toThreeUniform`, which doesn't seem ideal.

What would you think about preserving all of the small fixes and improvements in this change, but omitting the caching scheme for now, and we can consider this idea separately in the future?

2024-07-17 03:41 UTC, kwokcb commented
Sounds like a good separation. Maybe let's table looking at why "render" has so much overhead. It could be draw time, it could be uniform bind time or state setup time or something else. OpenPBR is the slowest shader but std surface is also good for testing.

2024-09-09 15:07 UTC, kwokcb commented
@jstone-lucasfilm, This is purely a texture caching update PR now.

2024-09-09 17:19 UTC, jstone-lucasfilm reviewed
This looks good to me, @kwokcb!  Is there a generated web site where we can validate these changes in the context of the viewer?

2024-09-09 17:20 UTC, jstone-lucasfilm approved these changes

2024-09-09 18:07 UTC, kwokcb commented
Hi @jstone-lucasfilm, I added a "data" example that can be used in the viewer. The "blob" case I can't really make it show unless the viewer page was loading the data. (I just showed it in my own editor which uses the same URI support but has UI to support setting local images -- basically what Felix logged an issue for that `MaterialXViewer` could support).

2024-09-11 15:32 UTC, jstone-lucasfilm commented
@kwokcb Oh, I wasn't suggesting that you should add anything more to the set of fixes that I reviewed.  I was just curious as to whether you had a generated web site where I could validate that the latest code worked well.

2024-09-11 17:38 UTC, kwokcb commented
Ah. My mistake. I reverted the last push. I tried publishing the viewer page from branch but didn't have any luck.

2024-09-16 00:19 UTC, jstone-lucasfilm commented
Thanks @kwokcb, and I'll give this a try in my own fork of MaterialX.

2024-09-16 15:35 UTC, merged